// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateTime(2002, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mehmet",
                            ImgUrl = "/images/studentImages/e1.png",
                            LastName = "Ekinci",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateTime(2001, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            ImgUrl = "/images/studentImages/e2.png",
                            LastName = "Yılmaz",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateTime(2002, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmet",
                            ImgUrl = "/images/studentImages/e3.png",
                            LastName = "Çelik",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 4,
                            BirthDate = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mehmet",
                            ImgUrl = "/images/studentImages/e4.png",
                            LastName = "Demir",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 5,
                            BirthDate = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zeynep",
                            ImgUrl = "/images/studentImages/k1.png",
                            LastName = "Kara",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 6,
                            BirthDate = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elif",
                            ImgUrl = "/images/studentImages/k2.png",
                            LastName = "Yurt",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 7,
                            BirthDate = new DateTime(2003, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fatma",
                            ImgUrl = "/images/studentImages/k3.png",
                            LastName = "Öztürk",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 8,
                            BirthDate = new DateTime(2002, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emine",
                            ImgUrl = "/images/studentImages/k4.png",
                            LastName = "Aydın",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 9,
                            BirthDate = new DateTime(2001, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ayşe",
                            ImgUrl = "/images/studentImages/k5.png",
                            LastName = "Güneş",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 10,
                            BirthDate = new DateTime(2002, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Burak",
                            ImgUrl = "/images/studentImages/e5.png",
                            LastName = "Koç",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 11,
                            BirthDate = new DateTime(2003, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emre",
                            ImgUrl = "/images/studentImages/e6.png",
                            LastName = "Arslan",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 12,
                            BirthDate = new DateTime(2002, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Oğuz",
                            ImgUrl = "/images/studentImages/e7.png",
                            LastName = "Turan",
                            isDeleted = false
                        },
                        new
                        {
                            StudentId = 13,
                            BirthDate = new DateTime(2001, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cem",
                            ImgUrl = "/images/studentImages/e8.png",
                            LastName = "Sönmez",
                            isDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
